### ISSUE TITLE
Using C language and crash when starting debugging on the website

### ISSUE THREAD

**Issue by Raylin0722** [NCAIC/Toolkit#10]
### Description

Use command npx -y ncaic run and push the start button on the website
It crashes immediately

### System Informations

ncaic 0.5.2
Checking for language support ...
  JavaScript : OK (node 16.16.0)
  TypeScript : X
           C : OK (gcc 9.4.0)
         C++ : OK (g++ 9.4.0)
      Python : OK (python 3.10.5)
          Go : X
        Rust : X

### Reproduction

1. npx -y ncaic run
2. start(on the website)
3. error message appear(below)

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:817:11)
    at Socket._write (node:net:829:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at file:///home/raylin/.npm/_npx/766da37dcd1e43b9/node_modules/ncaic/dist/index.js:502:48
    at new Promise (<anonymous>)
    at run2 (file:///home/raylin/.npm/_npx/766da37dcd1e43b9/node_modules/ncaic/dist/index.js:466:10)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

### Config File

title: 測試模式 Test Mode
teams:
    Team A:
        source: "agent3.c"
        color: "#1d4ed8"
    Team B:
        source: ""
        color: "#e11d48"
delay:
    step: 200
    set: 2000
competition:
    rule: double-sided
    matches:
        -
            type: empty
        -
            type: random
            count: 4
        -
            type: random
            count: 8
            ext: true
    timeout:
        step: 999999999
        set: 999999999

**Comment by JacobLinCool** [comment]
It seems that the Toolkit is writing some data into a closed stream (which can be the stdin of your program)
You can set the VERBOSE mode (by passing `VERBOSE=1` to the env var) and print some debug message into stderr in your program.

How to set env var in powershell: https://www.google.com/search?q=pwsh+set+environment+variable

**Comment by JacobLinCool** [comment]
Hi @Raylin0722! Anything to update?

If you are using cmd (or cmder), you can use `set VERBOSE=1` to set the env var.

In your program, after parsing the input, you can try `fprintf(stderr, "stone = %" PRId8 ", time = %lf\n", stone, time);` to print out the debug message.

If your program accepts the input data correctly, you should see the below messages in the terminal after running `ncaic run`:

```sh
...
---
Client connected 1
Competition started with 6 sets.
Team A played 6, 2
stone = 2, time = 999999.999000
Team B played 0, 0
Team A played 9, 2
stone = 2, time = 999999.936000
Team B played 5, 3
Team A played 5, 12
stone = 2, time = 999999.895000
Team B played 9, 11
Team A played 1, 12
stone = 2, time = 999999.841000
...
```

---

The tested config.yml:
```yml
title: 測試模式 Test Mode
teams:
    Team A:
        source: "rand.py"
        color: "#1d4ed8"
    Team B:
        source: "rand.c" # with modification of printing debug messages
        color: "#e11d48"
delay:
    step: 200
    set: 2000
competition:
    rule: double-sided
    matches:
        - type: empty
        - type: random
          count: 4
        - type: random
          count: 8
          ext: true
    timeout:
        step: 999999999
        set: 999999999
```
